[DESIGN-1109] Status icon component
cypress-io/cypress-design pull request #52
Opened 2022-07-21 19:37 UTC by mapsandapps

2022-07-21 19:37 UTC, ryanjwilke commented
Task linked: [DESIGN-1109 Status icons](https://app.clickup.com/t/18033298/DESIGN-1109)

2022-07-22 15:54 UTC, elevatebart requested changes
Real good PR,
I love the docs part!

Some small changes.

2022-07-22 15:54 UTC, elevatebart commented on components/StatusIcon/constants.ts
> +import { compileReactIconProperties } from '@cypress-design/react-icon'
Importing react items in the common areas will bork up the typescript of TSX. You can experience it if you open a vue file and look at `class` or the same in react `className`.

Please move this in the react component.

2022-07-22 15:54 UTC, elevatebart commented on components/StatusIcon/react/package.json
> +    "clsx": "*"
missing dependencies:

- `react-icon`
- `icon-registry`

2022-07-22 15:54 UTC, elevatebart commented on components/StatusIcon/vue/package.json
> +  },
missing dependency to `icon-registry` at least

2022-07-22 15:54 UTC, elevatebart commented on components/StatusIcon/vue/tsconfig.json
> +  "include": ["*.vue", "*.ts", "*.tsx", "../../../cypress/support/*.ts"]
add `../constants.ts`
```suggestion
  "include": ["*.vue", "*.ts", "*.tsx", "../../../cypress/support/*.ts", "../constants.ts"]
```

2022-07-22 15:54 UTC, elevatebart commented on icon-registry/icons/cancelled-outline_x16.svg
> +<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
If you omit the width and height, the icons look way better in Mac Finder

```suggestion
<svg viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
```
<img width="901" alt="Screen Shot 2022-07-22 at 10 53 00 AM" src="https://user-images.githubusercontent.com/5592465/180477066-5cb8cd7d-1fc2-475a-aef2-7bc48026f897.png">

2022-07-22 20:42 UTC, elevatebart approved these changes

2022-07-22 20:55 UTC, merged